FROM ruby:3.1.2-slim-bullseye

RUN apt-get clean && apt-get update -q \
    && apt-get install --assume-yes -q --no-install-recommends \
      curl \
      imagemagick \
      libpq-dev \
    && apt-get remove python3 \
    && curl -fsSL https://deb.nodesource.com/setup_19.x | bash - \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -q \
    && apt-get install --assume-yes -q --no-install-recommends ghostscript geoip-database shared-mime-info yarn nodejs \
    && apt-get autoremove --assume-yes \
    && rm -rf /var/lib/apt/lists \
    && rm -fr /var/cache/apt

# log the image build date
RUN echo "rails-run="$(date +"%Y-%m-%d %H:%M %Z") >> /DOCKER_IMAGE_BUILD_HISTORY