# This is a base image for a ruby app that also includes a local postgres server. Convenient for very few select use cases.
FROM ruby:3

WORKDIR /app

# Set-up to use a specific version of postgres
COPY ./apt.postgresql.org.sh apt.postgresql.org.sh

# Additional packages needed for compiling gems and supporting postgres server
RUN bash apt.postgresql.org.sh -v 11 && \
    apt-get update -q && \
    apt-get install --assume-yes -q --no-install-recommends build-essential git postgresql-client-11 postgresql-11 sudo gnupg

RUN date +"%Y-%m-%d %H:%M %Z" >> /etc/DOCKER_IMAGE_PATCH_DATE