# docker build -f Dockerfile.slim -t rails-run:2.7.2-slim-buster .
# docker tag xxx krsyoung/rails-run:2.7.2-slim-buster
# docker push krsyoung/rails-run:2.7.2-slim-buster 
FROM ruby:2.7.2-slim-buster

RUN apt-get update -q \
    && apt-get install --assume-yes -q --no-install-recommends \
      curl \
      imagemagick \
      libpq-dev \
    && apt-get remove python3 \
    && curl -sL https://deb.nodesource.com/setup_14.x | bash - \
    && curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -q \
    && apt-get install --assume-yes -q --no-install-recommends nodejs yarn \
    && apt-get autoremove --assume-yes \
    && rm -rf /var/lib/apt/lists \
    && rm -fr /var/cache/apt